#!/usr/bin/python

from .settings import Tables 


create_raw_table_sql = '''create table if not exists %s(receive_info_id int not null primary key auto_increment, uuid varchar(1000) character set utf8 collate utf8_bin, source_type varchar(50) character set utf8 collate utf8_bin, cust_system_code varchar(100) character set utf8 collate utf8_bin, receive_type varchar(30) character set utf8 collate utf8_bin, receive_time timestamp, receive_content MEDIUMTEXT, analysis_flg varchar(20) character set utf8 collate utf8_bin) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["receive_table"])


create_analysis_table_sql = '''create table if not exists %s(info_id int not null primary key auto_increment, receive_info_id VARCHAR(100) character set utf8 collate utf8_bin, customer_code VARCHAR(1000) character set utf8 collate utf8_bin, monitor_code varchar(100) character set utf8 collate utf8_bin, monitor_version varchar(100) character set utf8 collate utf8_bin, identity_code varchar(100) character set utf8 collate utf8_bin, kpi_assortment varchar(100) character set utf8 collate utf8_bin, kpi_name varchar(100) character set utf8 collate utf8_bin, kpi_value varchar(100) character set utf8 collate utf8_bin, alert_content MEDIUMTEXT, ip varchar(100) character set utf8 collate utf8_bin, alert_time varchar(100) character set utf8 collate utf8_bin, service_object varchar(100) character set utf8 collate utf8_bin, service_name varchar(100) character set utf8 collate utf8_bin, factory_name varchar(100) character set utf8 collate utf8_bin, model_name varchar(100) character set utf8 collate utf8_bin, sn varchar(100) character set utf8 collate utf8_bin, city varchar(100) character set utf8 collate utf8_bin, business_system varchar(100) character set utf8 collate utf8_bin, ma_dept varchar(100) character set utf8 collate utf8_bin, ma_user varchar(100) character set utf8 collate utf8_bin, ma_mobile varchar(100) character set utf8 collate utf8_bin, ma_email varchar(100) character set utf8 collate utf8_bin, analysised_time varchar(100) character set utf8 collate utf8_bin, auto_create_flg varchar(100) character set utf8 collate utf8_bin, in_service_flg varchar(100) character set utf8 collate utf8_bin, deal_status varchar(100) character set utf8 collate utf8_bin, create_on timestamp, modified_on timestamp DEFAULT CURRENT_TIMESTAMP) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["format_table"])

create_customer_system_table_sql = '''create table if not exists %s(id int not null primary key auto_increment, cust_system_code VARCHAR(100) character set utf8 collate utf8_bin, customer_code VARCHAR(1000) character set utf8 collate utf8_bin, customer_name VARCHAR(1000) character set utf8 collate utf8_bin, monitor_code varchar(100) character set utf8 collate utf8_bin, monitor_name varchar(100) character set utf8 collate utf8_bin, monitor_version varchar(100) character set utf8 collate utf8_bin, address varchar(100) character set utf8 collate utf8_bin, parameter varchar(100) character set utf8 collate utf8_bin, remark varchar(100) character set utf8 collate utf8_bin, active_flg varchar(100) character set utf8 collate utf8_bin, create_by varchar(100) character set utf8 collate utf8_bin, create_on timestamp, modified_by varchar(100) character set utf8 collate utf8_bin, modified_on timestamp DEFAULT CURRENT_TIMESTAMP) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["customer_system_table"])

create_rule_table_sql = '''create table if not exists %s(rule_id int not null primary key auto_increment, cust_system_code VARCHAR(100) character set utf8 collate utf8_bin, rule_name varchar(100) character set utf8 collate utf8_bin, kpi_criterionalert MEDIUMTEXT, active_flg varchar(20) character set utf8 collate utf8_bin, create_by varchar(100) character set utf8 collate utf8_bin, create_on timestamp, modified_by varchar(100) character set utf8 collate utf8_bin, modified_on timestamp DEFAULT CURRENT_TIMESTAMP) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["customer_alert_rule"])

create_case_matched_table_sql = '''create table if not exists %s(id int not null primary key auto_increment, info_id VARCHAR(100) character set utf8 collate utf8_bin, rule_name varchar(100) character set utf8 collate utf8_bin, rule_matched TEXT, kpis_and_content MEDIUMTEXT, deal_status varchar(100) character set utf8 collate utf8_bin, same_rule TEXT, created_on timestamp) engine=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin''' % (Tables["case_matched_rule"])
